version: '3.9'

services:
   donkeycar_gpu:
      image: donkeycar_gpu
      network_mode: "host"
      privileged: true
      stdin_open: true
      tty: true
      container_name: donkeycar_gpu_cont
      volumes:
         - /dev/bus/usb:/dev/bus/usb
         - /tmp/.X11-unix:/tmp/.X11-unix
      device_cgroup_rules:
         - 'c 189:* rmw'
      runtime: nvidia
      environment:
         - NVIDIA_VISIBLE_DEVICES=all
         - DISPLAY

   
   donkeycar_cpu:
      image: donkeycar_cpu
      network_mode: "host"
      privileged: true
      stdin_open: true
      tty: true
      container_name: donkeycar_cpu_cont
      volumes:
         - /dev/bus/usb:/dev/bus/usb
         - /tmp/.X11-unix:/tmp/.X11-unix
      device_cgroup_rules:
         - 'c 189:* rmw'
      environment:
         - DISPLAY
   
