version: '3.3'

services:
   donkeysim_gpu:
    image: donkeysim_gpu
    network_mode: "host"
    privileged: true
    stdin_open: true
    tty: true
    container_name: donkeysim_gpu_cont
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
   
   donkeysim_cpu:
    image: donkeysim_cpu
    network_mode: "host"
    privileged: true
    stdin_open: true
    tty: true
    container_name: donkeysim_cpu_cont
